set_property SRC_FILE_INFO {cfile:/home/avanpc/avanco/vivado_projects/dynamic_function_exchange/dfx_project/rm_template/rm_template.gen/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1/design_1_xbar_1_in_context.xdc rfile:../../../rm_template.gen/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1/design_1_xbar_1_in_context.xdc id:1 order:EARLY scoped_inst:i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_0/xbar} [current_design]
set_property SRC_FILE_INFO {cfile:/home/avanpc/avanco/vivado_projects/dynamic_function_exchange/dfx_project/rm_template/rm_template.gen/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0/design_1_auto_ds_0_in_context.xdc rfile:../../../rm_template.gen/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0/design_1_auto_ds_0_in_context.xdc id:2 order:EARLY scoped_inst:i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_0/s00_couplers/auto_ds} [current_design]
set_property SRC_FILE_INFO {cfile:/home/avanpc/avanco/vivado_projects/dynamic_function_exchange/dfx_project/rm_template/rm_template.gen/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0/design_1_auto_pc_0_in_context.xdc rfile:../../../rm_template.gen/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0/design_1_auto_pc_0_in_context.xdc id:3 order:EARLY scoped_inst:i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_0/s00_couplers/auto_pc} [current_design]
set_property SRC_FILE_INFO {cfile:/home/avanpc/avanco/vivado_projects/dynamic_function_exchange/dfx_project/rm_template/rm_template.gen/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0/design_1_axi_dma_0_0_in_context.xdc rfile:../../../rm_template.gen/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0/design_1_axi_dma_0_0_in_context.xdc id:4 order:EARLY scoped_inst:i_design_1_wrapper/design_1_i/custom_logic/axi_dma_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/avanpc/avanco/vivado_projects/dynamic_function_exchange/dfx_project/rm_template/rm_template.gen/sources_1/bd/design_1/ip/design_1_floating_point_0_0/design_1_floating_point_0_0/design_1_floating_point_0_0_in_context.xdc rfile:../../../rm_template.gen/sources_1/bd/design_1/ip/design_1_floating_point_0_0/design_1_floating_point_0_0/design_1_floating_point_0_0_in_context.xdc id:5 order:EARLY scoped_inst:i_design_1_wrapper/design_1_i/custom_logic/floating_point_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/avanpc/avanco/vivado_projects/dynamic_function_exchange/dfx_project/rm_template/rm_template.gen/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0/design_1_xbar_0_in_context.xdc rfile:../../../rm_template.gen/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0/design_1_xbar_0_in_context.xdc id:6 order:EARLY scoped_inst:i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_1/xbar} [current_design]
set_property SRC_FILE_INFO {cfile:/home/avanpc/avanco/vivado_projects/dynamic_function_exchange/dfx_project/rm_template/rm_template.gen/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0/design_1_auto_us_0_in_context.xdc rfile:../../../rm_template.gen/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0/design_1_auto_us_0_in_context.xdc id:7 order:EARLY scoped_inst:i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_1/s00_couplers/auto_us} [current_design]
set_property SRC_FILE_INFO {cfile:/home/avanpc/avanco/vivado_projects/dynamic_function_exchange/dfx_project/rm_template/rm_template.gen/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1/design_1_auto_us_1_in_context.xdc rfile:../../../rm_template.gen/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1/design_1_auto_us_1_in_context.xdc id:8 order:EARLY scoped_inst:i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_1/s01_couplers/auto_us} [current_design]
set_property SRC_FILE_INFO {cfile:/home/avanpc/avanco/vivado_projects/dynamic_function_exchange/dfx_project/rm_template/rm_template.gen/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0/design_1_auto_cc_0_in_context.xdc rfile:../../../rm_template.gen/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0/design_1_auto_cc_0_in_context.xdc id:9 order:EARLY scoped_inst:i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_1/m00_couplers/auto_cc} [current_design]
set_property SRC_FILE_INFO {cfile:/home/avanpc/avanco/vivado_projects/dynamic_function_exchange/dfx_project/rm_template/rm_template.gen/sources_1/bd/design_1/ip/design_1_axi_intc_0_0/design_1_axi_intc_0_0/design_1_axi_intc_0_0_in_context.xdc rfile:../../../rm_template.gen/sources_1/bd/design_1/ip/design_1_axi_intc_0_0/design_1_axi_intc_0_0/design_1_axi_intc_0_0_in_context.xdc id:10 order:EARLY scoped_inst:i_design_1_wrapper/design_1_i/custom_logic/axi_intc_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/avanpc/avanco/vivado_projects/dynamic_function_exchange/dfx_project/rm_template/rm_template.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_in_context.xdc rfile:../../../rm_template.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_in_context.xdc id:11 order:EARLY scoped_inst:i_design_1_wrapper/design_1_i/custom_logic/proc_sys_reset_0_240MHz} [current_design]
set_property SRC_FILE_INFO {cfile:/home/avanpc/avanco/vivado_projects/dynamic_function_exchange/dfx_project/rm_template/rm_template.gen/sources_1/bd/design_1/ip/design_1_dfx_axi_shutdown_man_0_0/design_1_dfx_axi_shutdown_man_0_0/design_1_dfx_axi_shutdown_man_0_0_in_context.xdc rfile:../../../rm_template.gen/sources_1/bd/design_1/ip/design_1_dfx_axi_shutdown_man_0_0/design_1_dfx_axi_shutdown_man_0_0/design_1_dfx_axi_shutdown_man_0_0_in_context.xdc id:12 order:EARLY scoped_inst:i_design_1_wrapper/design_1_i/dfx_axi_shutdown_man_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/avanpc/avanco/vivado_projects/dynamic_function_exchange/dfx_project/rm_template/rm_template.gen/sources_1/bd/design_1/ip/design_1_dfx_axi_shutdown_man_1_0/design_1_dfx_axi_shutdown_man_1_0/design_1_dfx_axi_shutdown_man_1_0_in_context.xdc rfile:../../../rm_template.gen/sources_1/bd/design_1/ip/design_1_dfx_axi_shutdown_man_1_0/design_1_dfx_axi_shutdown_man_1_0/design_1_dfx_axi_shutdown_man_1_0_in_context.xdc id:13 order:EARLY scoped_inst:i_design_1_wrapper/design_1_i/dfx_axi_shutdown_man_1} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_0/xbar/aclk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_0/xbar]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_0/s00_couplers/auto_ds/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_0/s00_couplers/auto_ds]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_0/s00_couplers/auto_pc/aclk]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_0/s00_couplers/auto_pc]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins i_design_1_wrapper/design_1_i/custom_logic/axi_dma_0/m_axi_mm2s_aclk]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins i_design_1_wrapper/design_1_i/custom_logic/axi_dma_0/m_axi_s2mm_aclk]
set_property src_info {type:SCOPED_XDC file:4 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins i_design_1_wrapper/design_1_i/custom_logic/axi_dma_0/s_axi_lite_aclk]
set_property src_info {type:SCOPED_XDC file:4 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells i_design_1_wrapper/design_1_i/custom_logic/axi_dma_0]
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins i_design_1_wrapper/design_1_i/custom_logic/floating_point_0/aclk]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells i_design_1_wrapper/design_1_i/custom_logic/floating_point_0]
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_1/xbar/aclk]
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_1/xbar]
set_property src_info {type:SCOPED_XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_1/s00_couplers/auto_us/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:7 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_1/s00_couplers/auto_us]
set_property src_info {type:SCOPED_XDC file:8 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_1/s01_couplers/auto_us/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:8 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_1/s01_couplers/auto_us]
set_property src_info {type:SCOPED_XDC file:9 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 4.167 [get_pins i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_1/m00_couplers/auto_cc/m_axi_aclk]
set_property src_info {type:SCOPED_XDC file:9 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_1/m00_couplers/auto_cc/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:9 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_1/m00_couplers/auto_cc]
set_property src_info {type:SCOPED_XDC file:10 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins i_design_1_wrapper/design_1_i/custom_logic/axi_intc_0/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:10 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells i_design_1_wrapper/design_1_i/custom_logic/axi_intc_0]
set_property src_info {type:SCOPED_XDC file:11 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 4.167 [get_pins i_design_1_wrapper/design_1_i/custom_logic/proc_sys_reset_0_240MHz/slowest_sync_clk]
set_property src_info {type:SCOPED_XDC file:11 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells i_design_1_wrapper/design_1_i/custom_logic/proc_sys_reset_0_240MHz]
set_property src_info {type:SCOPED_XDC file:12 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 4.167 [get_pins i_design_1_wrapper/design_1_i/dfx_axi_shutdown_man_0/clk]
set_property src_info {type:SCOPED_XDC file:12 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells i_design_1_wrapper/design_1_i/dfx_axi_shutdown_man_0]
set_property src_info {type:SCOPED_XDC file:13 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins i_design_1_wrapper/design_1_i/dfx_axi_shutdown_man_1/clk]
set_property src_info {type:SCOPED_XDC file:13 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells i_design_1_wrapper/design_1_i/dfx_axi_shutdown_man_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells i_design_1_wrapper/design_1_i]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_0/xbar]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_0/s00_couplers/auto_ds]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_0/s00_couplers/auto_pc]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells i_design_1_wrapper/design_1_i/custom_logic/axi_dma_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells i_design_1_wrapper/design_1_i/custom_logic/floating_point_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_1/xbar]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_1/s00_couplers/auto_us]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_1/s01_couplers/auto_us]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_1/m00_couplers/auto_cc]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells i_design_1_wrapper/design_1_i/custom_logic/axi_interconnect_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells i_design_1_wrapper/design_1_i/custom_logic/axi_intc_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells i_design_1_wrapper/design_1_i/custom_logic/xlconcat_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells i_design_1_wrapper/design_1_i/custom_logic/proc_sys_reset_0_240MHz]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells i_design_1_wrapper/design_1_i/dfx_axi_shutdown_man_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells i_design_1_wrapper/design_1_i/dfx_axi_shutdown_man_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells i_design_1_wrapper/design_1_i/xlconstant_1]
