# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/avanpc/avanco/vivado_projects/dynamic_function_exchange/dfx_project/rm_template_ila/rm_template.srcs/sources_1/bd/rm_design/ip/rm_design_proc_sys_reset_0_240MHz_0/rm_design_proc_sys_reset_0_240MHz_0.xci
# IP: The module: 'rm_design_proc_sys_reset_0_240MHz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/avanpc/avanco/vivado_projects/dynamic_function_exchange/dfx_project/rm_template_ila/rm_template.gen/sources_1/bd/rm_design/ip/rm_design_proc_sys_reset_0_240MHz_0/rm_design_proc_sys_reset_0_240MHz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'rm_design_proc_sys_reset_0_240MHz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/avanpc/avanco/vivado_projects/dynamic_function_exchange/dfx_project/rm_template_ila/rm_template.gen/sources_1/bd/rm_design/ip/rm_design_proc_sys_reset_0_240MHz_0/rm_design_proc_sys_reset_0_240MHz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'rm_design_proc_sys_reset_0_240MHz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/avanpc/avanco/vivado_projects/dynamic_function_exchange/dfx_project/rm_template_ila/rm_template.gen/sources_1/bd/rm_design/ip/rm_design_proc_sys_reset_0_240MHz_0/rm_design_proc_sys_reset_0_240MHz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rm_design_proc_sys_reset_0_240MHz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/avanpc/avanco/vivado_projects/dynamic_function_exchange/dfx_project/rm_template_ila/rm_template.srcs/sources_1/bd/rm_design/ip/rm_design_proc_sys_reset_0_240MHz_0/rm_design_proc_sys_reset_0_240MHz_0.xci
# IP: The module: 'rm_design_proc_sys_reset_0_240MHz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/avanpc/avanco/vivado_projects/dynamic_function_exchange/dfx_project/rm_template_ila/rm_template.gen/sources_1/bd/rm_design/ip/rm_design_proc_sys_reset_0_240MHz_0/rm_design_proc_sys_reset_0_240MHz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'rm_design_proc_sys_reset_0_240MHz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/avanpc/avanco/vivado_projects/dynamic_function_exchange/dfx_project/rm_template_ila/rm_template.gen/sources_1/bd/rm_design/ip/rm_design_proc_sys_reset_0_240MHz_0/rm_design_proc_sys_reset_0_240MHz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'rm_design_proc_sys_reset_0_240MHz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/avanpc/avanco/vivado_projects/dynamic_function_exchange/dfx_project/rm_template_ila/rm_template.gen/sources_1/bd/rm_design/ip/rm_design_proc_sys_reset_0_240MHz_0/rm_design_proc_sys_reset_0_240MHz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rm_design_proc_sys_reset_0_240MHz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
